'use server';
/**
 * @fileOverview A Genkit flow for generating contextual strategic advice and warnings for startup founders.
 *
 * - contextualStrategicAdvisor - A function that handles the advice generation process.
 * - ContextualStrategicAdvisorInput - The input type for the contextualStrategicAdvisor function.
 * - ContextualStrategicAdvisorOutput - The return type for the contextualStrategicAdvisor function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ContextualStrategicAdvisorInputSchema = z.object({
  // Company Basics
  companyName: z.string().describe('The name of the company.'),
  stage: z.enum(['idea', 'mvp', 'seed', 'seriesa', 'seriesb']).describe('The current funding stage of the company.'),
  industry: z.enum(['iot', 'saas', 'edtech', 'ecomm', 'fintech', 'healthtech', 'ai']).describe('The industry the company operates in.'),

  // Revenue & Traction Signals
  monthlyRevenue: z.number().min(0).describe('Current monthly recurring revenue (MRR) in INR.'),
  monthlyGrowthRate: z.number().min(0).max(500).describe('Monthly growth rate percentage (e.g., 15 for 15%).'),
  monthlyBurnRate: z.number().min(0).describe('Monthly burn rate in INR.'),
  cashInBank: z.number().min(0).describe('Current cash in bank in INR.'),
  totalCustomers: z.number().min(0).describe('Total number of paying customers.'),
  avgCustomerLTV: z.number().min(0).describe('Average customer Lifetime Value (LTV) in INR.'),
  customerAcquisitionCost: z.number().min(0).describe('Customer Acquisition Cost (CAC) in INR.'),

  // Investment Deal Terms
  investmentAmount: z.number().min(0).describe('Amount of investment sought/received in the current round in INR.'),
  equityOfferedToInvestor: z.number().min(0).max(100).describe('Percentage of equity offered to the investor in the current round.'),
  esopPoolPercentage: z.number().min(0).max(50).describe('Percentage of ESOP pool.'),
  advisorEquityPercentage: z.number().min(0).max(20).describe('Percentage of equity allocated to advisors.'),
  coFounderEquityPercentage: z.number().min(0).max(80).describe('Percentage of equity allocated to co-founders.'),

  // Calculated Valuation Metrics (as derived from UI logic)
  preMoneyValuation: z.number().min(0).describe('Pre-money valuation in INR based on VC method calculation.'),
  postMoneyValuation: z.number().min(0).describe('Post-money valuation in INR based on VC method calculation.'),
  revenueMultipleBasedValuation: z.number().min(0).describe('Revenue multiple based valuation in INR calculation.'),
  berkusScoreValuation: z.number().min(0).describe('Berkus Score based valuation in INR calculation.'),
  impliedRevenueMultiple: z.number().min(0).describe('Implied revenue multiple of pre-money valuation (pre-money / ARR). Can be 0 if ARR is 0.'),

  // Calculated Equity Metrics
  currentFounderEquityPercentage: z.number().min(0).max(100).describe('Current founder equity percentage (after accounting for co-founder, investor, ESOP, advisor).'),

  // Financial Health Metrics (as derived from UI logic)
  runwayMonths: z.number().min(0).describe('Calculated runway in months (Cash in Bank / Monthly Burn Rate).'),
  ltvToCacRatio: z.number().min(0).describe('Calculated LTV to CAC ratio (Avg LTV / CAC).'),
  cacPaybackMonths: z.number().min(0).describe('Calculated CAC Payback period in months.'),
  projectedAnnualRevenue12Months: z.number().min(0).describe('Projected Annual Revenue after 12 months in INR.'),

  // Funding Round Dilution Simulation
  dilutionRounds: z.array(z.object({
    name: z.string().describe('Name of the funding round (e.g., Seed, Series A).'),
    investment: z.number().min(0).describe('Investment amount for this round in INR.'),
    equity: z.number().min(0).max(100).describe('Equity offered in this round in percentage.'),
  })).describe('Simulated future funding rounds.'),
  founderEquityAfterAllDilution: z.number().min(0).max(100).describe('Founder equity percentage after all simulated dilution rounds.'),
  dilutionSummaryWarning: z.string().optional().describe('An optional warning string generated by the UI about the overall dilution outcome.'),


  // Liquidation Preference (as derived from UI logic)
  exitPrice: z.number().min(0).describe('Simulated exit/acquisition price in INR.'),
  totalInvestorCapitalInvested: z.number().min(0).describe('Total capital invested by all investors in INR.'),
  liquidationPreferenceMultiple: z.number().min(1).max(3).describe('Liquidation preference multiple (e.g., 1, 1.5, 2, 3).'),
  liquidationPreferenceType: z.enum(['nonparticipating', 'participating']).describe('Type of liquidation preference (non-participating or participating).'),
  investorReceivesAtExit: z.number().min(0).describe('Amount investor receives at simulated exit in INR.'),
  founderReceivesAtExit: z.number().min(0).describe('Amount founder receives at simulated exit in INR.'),
  liquidationWarningMessage: z.string().optional().describe('An optional warning message generated by the UI regarding liquidation outcome (e.g., investor takes all).'),


  // Cap Table & Authority Checks (Summarized from UI's logic)
  totalCapTablePercentage: z.number().min(0).max(101).describe('Total ownership percentage in the cap table.'), // Can slightly exceed 100% due to floating point or errors
  capTableAlerts: z.array(z.string()).describe('List of alerts generated by the cap table tracker (e.g., total > 100%, unallocated shares).'),
  founderVotingMajorityCheck: z.boolean().describe('True if founders are projected to hold a voting majority (>50%).'),
  investorPreferenceSharesHealth: z.enum(['healthy', 'high_investor_pref']).describe('Status of investor preference shares percentage (healthy or too high, e.g., >40%).'),
  singleInvestorDominanceHealth: z.enum(['healthy', 'dominant_investor']).describe('Status regarding single investor dominance (healthy or dominant, e.g., single investor holds >30%).'),
  esopPoolHealth: z.enum(['healthy', 'too_low', 'too_high']).describe('Status of ESOP pool (healthy: 5-15%, too low: <5%, or too high: >15%).'),
  founderEquityHealthStatus: z.enum(['critically_low', 'low', 'healthy']).describe('Health status of current founder equity percentage (healthy: >=40%, low: 25-40%, critically_low: <25%).'),
});

export type ContextualStrategicAdvisorInput = z.infer<typeof ContextualStrategicAdvisorInputSchema>;

const ContextualStrategicAdvisorOutputSchema = z.object({
  summary: z.string().describe('An overall summary of the company’s current status.'),
  strengths: z.array(z.string()).describe('Key strengths identified from the provided data.'),
  warnings: z.array(z.string()).describe('Critical warnings or potential risks.'),
  recommendations: z.array(z.string()).describe('Actionable recommendations for growth and protection.'),
});
export type ContextualStrategicAdvisorOutput = z.infer<typeof ContextualStrategicAdvisorOutputSchema>;

export async function contextualStrategicAdvisor(input: ContextualStrategicAdvisorInput): Promise<ContextualStrategicAdvisorOutput> {
  return contextualStrategicAdvisorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'contextualStrategicAdvisorPrompt',
  input: { schema: ContextualStrategicAdvisorInputSchema },
  output: { schema: ContextualStrategicAdvisorOutputSchema },
  prompt: `You are an expert startup advisor for Indian founders. Your task is to analyze the provided company data and generate a concise, actionable report in JSON format.
This report should include:
- An overall 'summary' of the company's current status and key observations.
- An array of 'strengths' identified from the provided data.
- An array of 'warnings' for critical risks the founder should be aware of, explaining why they are risks.
- An array of 'recommendations' to address weaknesses, mitigate risks, and optimize for growth and protection, with a focus on immediate next steps.

Always refer to "the founder" or "your company" in your advice. Focus on the most impactful points.
Be direct and use Indian startup context where appropriate (e.g., INR, typical Indian seed rounds, specific regulations if applicable from the UI's glossary hints).
Emphasize strategic advice over just stating numbers.

Here is the company data:

**Company Profile:**
- Company Name: {{{companyName}}}
- Stage: {{{stage}}}
- Industry: {{{industry}}}

**Financial & Traction Metrics:**
- Monthly Recurring Revenue (MRR): ₹{{{monthlyRevenue}}}
- Monthly Growth Rate: {{{monthlyGrowthRate}}}%
- Monthly Burn Rate: ₹{{{monthlyBurnRate}}}
- Cash in Bank: ₹{{{cashInBank}}}
- Calculated Runway: {{{runwayMonths}}} months
- Total Customers: {{{totalCustomers}}}
- Average Customer LTV: ₹{{{avgCustomerLTV}}}
- Customer Acquisition Cost (CAC): ₹{{{customerAcquisitionCost}}}
- LTV:CAC Ratio: {{{ltvToCacRatio}}}x
- CAC Payback Period: {{{cacPaybackMonths}}} months
- Projected Annual Revenue (12 months): ₹{{{projectedAnnualRevenue12Months}}}

**Current Investment & Equity Structure:**
- Investment Amount (current round): ₹{{{investmentAmount}}}
- Equity Offered to Investor (current round): {{{equityOfferedToInvestor}}}%
- ESOP Pool: {{{esopPoolPercentage}}}%
- Advisor Equity: {{{advisorEquityPercentage}}}%
- Co-founder Equity: {{{coFounderEquityPercentage}}}%
- Your (Primary Founder) Current Equity: {{{currentFounderEquityPercentage}}}%

**Valuation Insights:**
- Pre-Money Valuation (VC Method): ₹{{{preMoneyValuation}}}
- Post-Money Valuation (VC Method): ₹{{{postMoneyValuation}}}
- Revenue Multiple Based Valuation: ₹{{{revenueMultipleBasedValuation}}}
- Berkus Score Valuation: ₹{{{berkusScoreValuation}}}
- Implied Revenue Multiple (Pre-money / ARR): {{{impliedRevenueMultiple}}}x (Compare this against industry average)

**Dilution Simulation:**
- Future Funding Rounds Simulated:
{{#each dilutionRounds}}
  - Round Name: {{this.name}}, Investment: ₹{{this.investment}}, Equity Offered: {{this.equity}}%
{{/each}}
- Your Equity After All Simulated Dilution: {{{founderEquityAfterAllDilution}}}%
- Dilution Summary Warning: {{{dilutionSummaryWarning}}}

**Liquidation Preference Analysis:**
- Simulated Exit Price: ₹{{{exitPrice}}}
- Total Investor Capital Invested: ₹{{{totalInvestorCapitalInvested}}}
- Liquidation Preference Multiple: {{{liquidationPreferenceMultiple}}}x
- Liquidation Preference Type: {{{liquidationPreferenceType}}}
- Amount Investor Receives at Exit: ₹{{{investorReceivesAtExit}}}
- Amount Founder Receives at Exit: ₹{{{founderReceivesAtExit}}}
- Liquidation Warning Message: {{{liquidationWarningMessage}}}

**Cap Table & Authority Health Checks:**
- Total Cap Table Ownership Percentage: {{{totalCapTablePercentage}}}%
- Cap Table Alerts: {{#if capTableAlerts.length}}{{#each capTableAlerts}}
  - {{this}}{{/each}}{{else}}None{{/if}}
- Founder Voting Majority: {{#if founderVotingMajorityCheck}}Yes (Founders retain >50% voting power){{else}}No (Founders may not retain voting majority){{/if}}
- Investor Preference Shares Status: {{{investorPreferenceSharesHealth}}} (Investor preference shares are at {{{investorPreferenceSharesPercentage}}}%)
- Single Investor Dominance: {{{singleInvestorDominanceHealth}}} (A single investor holding >30% could block decisions)
- ESOP Pool Status: {{{esopPoolHealth}}} (ESOP pool percentage is {{{esopPoolPercentage}}}%)
- Founder Equity Health Status: {{{founderEquityHealthStatus}}} (Current founder equity: {{{currentFounderEquityPercentage}}}%)

Based on this comprehensive data, generate the report.`,
});

const contextualStrategicAdvisorFlow = ai.defineFlow(
  {
    name: 'contextualStrategicAdvisorFlow',
    inputSchema: ContextualStrategicAdvisorInputSchema,
    outputSchema: ContextualStrategicAdvisorOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);